name: C/C++ CI

on:
  push:
    branches: [ next, module ]
  pull_request:
    branches: [ next, module ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add build-base git bash cmake
    
    - name: Compile project
      run: make
    
    - uses: actions/upload-artifact@v4
      with:
        path: |
          audio_driver/audio_driver.prx
          display_driver/display_driver.prx
          fs_driver/fs_driver.prx
          app/EBOOT.PBP
