name: C/C++ CI

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add build-base git bash cmake
    
    - name: Compile project
      run: make

    - name: Prepare artifact folder
      run: |
        mkdir -p CMFileManagerPSP
        cp audio_driver/audio_driver.prx CMFileManagerPSP/
        cp display_driver/display_driver.prx CMFileManagerPSP/
        cp fs_driver/fs_driver.prx CMFileManagerPSP/
        cp app/EBOOT.PBP CMFileManagerPSP/

    - uses: actions/upload-artifact@v4
      with:
        name: CMFileManagerPSP
        path: CMFileManagerPSP/
